dist:
  module: github.com/G-Research/otel-partial-span
  name: otel-partial-span
  description: Open telemetry exporter
  output_path: ./bin
  version: 0.1.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.121.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.121.0
  - gomod: github.com/G-Research/otel-partial-connector v0.1.0
    import: github.com/G-Research/otel-partial-connector/otelpartialexporter
    name: otelpartialexporter

processors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor v0.121.0
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.121.0


receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.121.0
  - gomod: github.com/G-Research/otel-partial-connector v0.1.0
    import: github.com/G-Research/otel-partial-connector/otelpartialreceiver
    name: otelpartialreceiver

replaces:
  - github.com/G-Research/otel-partial-connector => ../
