dist:
  module: github.com/G-Research/partialconnector/cmd
  name: partialconnector
  description: Connector for partial log traces
  output_path: ./cmd
  version: 0.1.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.119.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.119.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.119.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.119.0

connectors:
  - gomod: github.com/G-Research/partialconnector v0.1.0

replaces:
  - github.com/G-Research/partialconnector => ../
