dist:
  module: github.com/G-Research/otel-partial-collector
  name: otel-partial-collector
  description: Open telemetry partial collector
  output_path: ./bin
  version: 0.3.1

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.124.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.124.0
  - gomod: github.com/G-Research/otel-partial-collector/exporter/otelpartialexporter v0.3.1

processors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor v0.124.1
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.124.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.124.0
  - gomod: github.com/G-Research/otel-partial-collector/receiver/otelpartialreceiver v0.3.1

replaces:
  - github.com/G-Research/otel-partial-collector/receiver/otelpartialreceiver => ../receiver/otelpartialreceiver
  - github.com/G-Research/otel-partial-collector/exporter/otelpartialexporter => ../exporter/otelpartialexporter
  - github.com/G-Research/otel-partial-collector/internal/postgres => ../internal/postgres
