receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  otelpartialreceiver:
    postgres: "postgres://postgres:test@127.0.0.1:40444/otelpartialcollector?sslmode=disable"
    gc_interval: "5s"

exporters:
  debug:
  otelpartialexporter:
    postgres: "postgres://postgres:test@127.0.0.1:40444/otelpartialcollector?sslmode=disable"
    expiry_factor: 3

processors:
  batch:
    send_batch_size: 50
    send_batch_max_size: 100
    timeout: 1s
  groupbyattrs:
  groupbytrace:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otelpartialexporter]
    traces:
      receivers: [otelpartialreceiver]
      processors: [groupbytrace, groupbyattrs, batch]
      exporters: [debug]
