receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  otelpartialreceiver:
    postgres: "postgres://postgres:test@127.0.0.1:40444/otelpartialcollector?sslmode=disable"
    gc_interval: "5s"
    batch_max_size: 100

exporters:
  debug:
  otelpartialexporter:
    postgres: "postgres://postgres:test@127.0.0.1:40444/otelpartialcollector?sslmode=disable"
    expiry_factor: 3
    retry_on_failure:
      initial_interval: 5s
    sending_queue:
      queue_size: 1000
      batch:
        flush_timeout: 1s
        min_size: 50
        max_size: 100

processors:
  batch:
  groupbyattrs:
  groupbytrace:

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [otelpartialexporter]
    traces:
      receivers: [otelpartialreceiver]
      processors: [groupbytrace, groupbyattrs, batch]
      exporters: [debug]
