receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  otelpartialreceiver:
    postgres: "postgres://postgres:test@127.0.0.1:40444/otelpartialconnector?sslmode=disable"
    interval: "24h"

exporters:
  debug:
  otelpartialexporter:
    postgres: "postgres://postgres:test@127.0.0.1:40444/otelpartialconnector?sslmode=disable"

processors:
  batch:
  groupbytrace:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otelpartialexporter]
    traces:
      receivers: [otelpartialreceiver]
      processors: [groupbytrace]
      exporters: [debug]
