receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:

processors:
  batch:

connectors:
  otelpartialconnector:
    postgres: "postgres://postgres:test@127.0.0.1:40444/otelpartialconnector?sslmode=disable"
    gc_older_than: "24h"

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otelpartialconnector]
    traces:
      receivers: [otelpartialconnector]
      exporters: [debug]
