dist:
  module: github.com/G-Research/otel-partial-connector/cmd/otel-partial-receiver
  name: otel-partial-receiver
  description: Open telemetry partial receiver
  output_path: ./cmd/otel-partial-receiver
  go: 1.24.0
  version: 0.1.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.119.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.119.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.119.0

receivers:
  - gomod: github.com/G-Research/otel-partial-connector v0.1.0
    import: github.com/G-Research/otel-partial-connector/otelpartialreceiver
    name: otelpartialreceiver

replaces:
  - github.com/G-Research/otel-partial-connector => ../../
