dist:
  module: github.com/G-Research/otel-partial-connector/cmd/otel-partial-receiver
  name: otelpartialconnector
  description: Open telemetry receiver
  output_path: ./cmd/otel-partial-receiver
  version: 0.1.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.119.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.119.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.119.0

receivers:
  - gomod: github.com/G-Research/otel-partial-connector/otelpartialreceiver v0.1.0
