// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

module github.com/G-Research/otel-partial-connector/cmd

go 1.22

require (
	go.opentelemetry.io/collector/confmap/provider/envprovider v1.27.0
	go.opentelemetry.io/collector/confmap/provider/fileprovider v1.27.0
	go.opentelemetry.io/collector/confmap/provider/httpprovider v1.27.0
	go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.27.0
	go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.27.0
	go.opentelemetry.io/collector/receiver/otlpreceiver v0.119.0
	go.opentelemetry.io/collector/exporter/debugexporter v0.119.0
	go.opentelemetry.io/collector/exporter/otlpexporter v0.119.0
	github.com/G-Research/otel-partial-connector v0.1.0
	go.opentelemetry.io/collector/processor/batchprocessor v0.119.0
	go.opentelemetry.io/collector/otelcol v0.121.0
)

require (
	github.com/knadh/koanf/maps v0.1.1 // indirect
	github.com/knadh/koanf/providers/confmap v0.1.0 // indirect
)










replace github.com/G-Research/otel-partial-connector => ../../
